---
name: etcd
director_uuid: b02f8ab5-b63c-4f08-b144-89f96810a022

releases:
- name: {{.Name}}
  version: latest

compilation:
  cloud_properties:
    name: random
  network: etcd1
  reuse_compilation_vms: true
  workers: 6

jobs:
- instances: 1
  name: etcd_z1
  networks:
  - name: etcd1 
    static_ips:
    - 10.244.0.2
  persistent_disk: 10024
  properties:
    metron_agent:
      zone: z1
    networks:
      apps: etcd1
  resource_pool: medium_z1
  templates:
  - name: {{.Name}} 
    release: etcd 
  update:
    max_in_flight: 1

properties:
  etcd:
    ca_cert: null
    client_cert: null
    client_key: null
    cluster: null
    machines:
    - 10.244.0.2
    peer_require_ssl: null
    require_ssl: null
    server_cert: null
    server_key: null

networks:
- name: etcd1 
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.0.0/24
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2

resource_pools:
- cloud_properties:
    name: random
  name: medium_z1
  network: etcd1 
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 0
  canary_watch_time: 1000-180000
  max_in_flight: 50
  serial: true
  update_watch_time: 1000-180000
