iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: turbulence 
      cloud_properties: {}

  subnet_configs:
    - name: turbulence
      subnets:
      - cloud_properties:
          name: random
        range: 10.244.7.0/30
        reserved:
        - 10.244.7.1
        static:
        - 10.244.7.2
    - name: compilation
      subnets:
      - cloud_properties:
          name: random
        range: 10.244.8.0/30
        reserved:
        - 10.244.8.1
        static: []
      - cloud_properties:
          name: random
        range: 10.244.8.4/30
        reserved:
        - 10.244.8.5
        static: []
      - cloud_properties:
          name: random
        range: 10.244.8.8/30
        reserved:
        - 10.244.8.9
        static: []
